name: CI

on:
  pull_request:
  release:
    types: [published]

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Run tests
      run: |
        set -euo pipefail
        python3 -m venv env
        source env/bin/activate
        pip install -r requirements.txt
        maturin develop
        python -m unittest

  linux:
    if: >
      github.event_name == 'release' && github.event.action == 'published'
    needs: [ tests ]
    strategy:
      fail-fast: true
      matrix:
        platform:
          - target: x86_64
            manylinux: auto
          - target: aarch64
            manylinux: auto
          - target: x86_64-unknown-linux-musl
            manylinux: musllinux_1_2
            container: quay.io/pypa/musllinux_1_2_x86_64
          - target: aarch64-unknown-linux-musl
            manylinux: musllinux_1_2
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Build wheels
      uses: PyO3/maturin-action@v1
      with:
        command: build
        rust-toolchain: stable
        manylinux: ${{ matrix.platform.manylinux }}
        target: ${{ matrix.platform.target }}
        container: ${{ matrix.platform.container }}
        args: --release -o dist --find-interpreter
    - name: Upload wheels
      uses: actions/upload-artifact@v4
      with:
        name: wheel-linux-${{ matrix.platform.target }}
        path: dist/*
        retention-days: 1

  windows:
    if: >
      github.event_name == 'release' && github.event.action == 'published'
    needs: [ tests ]
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v4
    - name: Build wheels
      uses: PyO3/maturin-action@v1
      with:
        command: build
        rust-toolchain: stable
        args: --release -o dist --find-interpreter
    - name: Upload wheels
      uses: actions/upload-artifact@v4
      with:
        name: wheel-windows
        path: dist/*
        retention-days: 1

  macos:
    if: >
      github.event_name == 'release' && github.event.action == 'published'
    needs: [ tests ]
    strategy:
      fail-fast: true
      matrix:
        target:
          - aarch64-apple-darwin
          - x86_64-apple-darwin
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v4
    - name: Build wheels
      uses: PyO3/maturin-action@v1
      with:
        command: build
        rust-toolchain: stable
        args: --release -o dist --find-interpreter --target ${{ matrix.target }}
    - name: Upload wheels
      uses: actions/upload-artifact@v4
      with:
        name: wheel-macos-${{ matrix.target }}
        path: dist/*
        retention-days: 1
  
  publish_testpypi:
    name: Publish to test.pypi.org
    runs-on: ubuntu-latest
    if: >
      github.event_name == 'release' && github.event.action == 'published' && github.event.release.prerelease == true
    needs: [ macos, windows, linux ]
    permissions:
      id-token: write
    environment: testpypi
    steps:
      - uses: actions/download-artifact@v4
        with:
          path: dist
          merge-multiple: true
      - uses: pypa/gh-action-pypi-publish@release/v1
        with:
          repository-url: https://test.pypi.org/legacy/

  publish_pypi:
    name: Publish to pypi.org
    runs-on: ubuntu-latest
    if: >
      github.event_name == 'release' && github.event.action == 'published' && github.event.release.prerelease == false
    needs: [ macos, windows, linux ]
    permissions:
      id-token: write
    environment: testpypi
    steps:
      - uses: actions/download-artifact@v4
        with:
          path: dist
          merge-multiple: true
      - uses: pypa/gh-action-pypi-publish@release/v1
